### ISSUE TITLE
ability to disable a plugin upon command 

### ISSUE THREAD

**Issue by Ollie2000** [prism/Bedrock#21]
you know, in case something goes really buggy and it needs to be disabled and can't wait for a reboot

**Comment by Aiden880** [comment]
I don't think this is such a good idea, there was a plugin that used to do this for Bukkit and everyone seemed to advise completely against it, saying it caused them loads of issues with crashing and corruption.

**Comment by viveleroi** [comment]
Disabling plugins after they've loaded is a bad practice anyway. I don't know that Sponge even allows it but it's certainly frowned upon.
