### ISSUE TITLE
home limiting

### ISSUE THREAD

**Issue by Ollie2000** [prism/Bedrock#40]
I remember a while ago with old spigot and essentials there was a config option to change, add and remove perm nodes, so it went a little like this

bedrock.homes.trusted = 10
bedrock.homes.respected = 25
bedrock.homes.eternal = 250
bedrock.homes.newmod = 1000

you'd set all these up in the config then when it comes to applying the perm nodes it already knows how many homes each rank has without adding more lines to the pex file like it currently does.

I don't know how easy this is, but I thought it was neat. whichever way you decide to go is cool

**Comment by viveleroi** [comment]
Homes can already be limited by options on a per-rank basis, so we'll keep it with that system.
