### ISSUE TITLE
some commands return error messages

### ISSUE THREAD

**Issue by SpongeGuy** [prism/Bedrock#85]
Hello, I am testing a modded 1.11.2 server with your plugin installed.
Most of the commands included work, but a few return errors, like /vanish, /sethome, and /warp.

For /vanish, when I enter this in, it makes me invisible (besides armor), but returns
```
Error occurred while executing command:
INVISIBILITY_IGNORES_COLLISION
```

For /sethome, I'll use `/sethome h`.  When I enter this in, the game returns
```
Error occurred while executing command:
org/spongepowered/api/service/permission/option/OptionSubject
```

For /warp, /setwarp w returns no errors, but when I try to warp to w using /warp w, the game returns
```
Error occurred while executing command:
org.spongepowered.api.entity.living.player.Player.setLocation(Lorg/spongepowered/api/world/Location;)V
```

If you need any information I missed, please tell me.

**Comment by viveleroi** [comment]
The last two pastes don't seem to include any actual error message, but I'm sure all three of these are due to API changes, I just haven't kept this up. There are probably some better alternatives at this point, but I'd welcome PRs if anyone is interested.
